function plotOUTLposVelErrorNorms(log, der, pp)
% Plot translational position and velocity error norms vs time

set(figure,'Color','white','WindowState','maximized')

% Position error norm
subplot(2,1,1)
plot(log.time, der.translational_position_error.norm, ...
     'b-', 'LineWidth', 2)
ylabel('Position error norm [m]', ...
       'Interpreter','latex', ...
       'FontSize', pp.font_size)
title(pp.folder_controller, ...
      'Interpreter','latex', ...
      'FontSize', pp.font_size_title)
axis tight
xlim([pp.x_lim_min, pp.x_lim_max])

% Velocity error norm
subplot(2,1,2)
plot(log.time, der.translational_velocity_error.norm, ...
     'b-', 'LineWidth', 2)
xlabel('$t$ [s]', ...
       'Interpreter','latex', ...
       'FontSize', pp.font_size)
ylabel('Velocity error norm [m/s]', ...
       'Interpreter','latex', ...
       'FontSize', pp.font_size)
axis tight
xlim([pp.x_lim_min, pp.x_lim_max])

end
