function K_hat_state_dot = adaptiveLawDeadzoneEmodification( ...
  Gamma_gain, ...
  dead_zone_value, ...
  pi_vector, ...
  tracking_error, ...
  P_mat, ...
  B_mat, ...
  sigma_gain, ...
  K_hat_state)
%ADAPTIVELAWDEADZONEEMODIFICATION Adaptive law equipped with dead-zone
%modification and e-modification

eTranspose_P_B = tracking_error' * P_mat * B_mat;

K_hat_state_dot = Gamma_gain * dead_zone_value * ( ...
  pi_vector * eTranspose_P_B ...
  - sigma_gain * norm(eTranspose_P_B) * K_hat_state);


end

