function plotINNLEulerAnglesErrors(log, der, pp)
% Plot Euler angle tracking errors (roll, pitch, yaw) in one plot

set(figure,'Color','white','WindowState','maximized')

plot(log.time, rad2deg(der.rotational_error.roll),  'r-', 'LineWidth', 1.5); hold on
plot(log.time, rad2deg(der.rotational_error.pitch), 'b--','LineWidth', 1.5)
plot(log.time, rad2deg(der.rotational_error.yaw),   'k-.','LineWidth', 1.5)

ylabel('Euler angle error [deg]', ...
       'Interpreter','latex', ...
       'FontSize', pp.font_size)
xlabel('$t$ [s]', ...
       'Interpreter','latex', ...
       'FontSize', pp.font_size)

legend({ ...
  'Roll error', ...
  'Pitch error', ...
  'Yaw error'}, ...
  'Interpreter','latex', ...
  'Location','best')

title(pp.folder_controller, ...
      'Interpreter','latex', ...
      'FontSize', pp.font_size_title)

axis tight
xlim([pp.x_lim_min, pp.x_lim_max])
% grid on
hold off

end
