function der = PyC_computeDerivedValues(log)


% Position error
der.translational_position_error.x = log.position.x - ...   
                                     log.user_defined_position.x;
der.translational_position_error.y = log.position.y - ...   
                                     log.user_defined_position.y;
der.translational_position_error.z = log.position.z - ...   
                                     log.user_defined_position.z;
der.translational_position_error.norm = ...
    vecnorm([der.translational_position_error.x, ...
             der.translational_position_error.y, ...
             der.translational_position_error.z]')';

% Velocity error
der.translational_velocity_error.x = log.velocity.x - ...   
                                     log.user_defined_velocity.x;
der.translational_velocity_error.y = log.velocity.y - ...   
                                     log.user_defined_velocity.y;
der.translational_velocity_error.z = log.velocity.z - ...   
                                     log.user_defined_velocity.z;

% Total thrust
der.total_thrust_motors_N = log.thrust_motors_N.T1 + ... 
                            log.thrust_motors_N.T2 + ...
                            log.thrust_motors_N.T3 + ...
                            log.thrust_motors_N.T4 + ...
                            log.thrust_motors_N.T5 + ... 
                            log.thrust_motors_N.T6 + ...
                            log.thrust_motors_N.T7 + ...
                            log.thrust_motors_N.T8;


end


